/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as TosImport } from './routes/tos'
import { Route as RegisterImport } from './routes/register'
import { Route as LoginImport } from './routes/login'
import { Route as ContactImport } from './routes/contact'
import { Route as AboutImport } from './routes/about'
import { Route as IndexImport } from './routes/index'
import { Route as PasswordResetImport } from './routes/password.reset'
import { Route as PasswordForgotImport } from './routes/password.forgot'
import { Route as EmailVerifyImport } from './routes/email.verify'
import { Route as ProtectedSettingsImport } from './routes/_protected/settings'
import { Route as ProtectedProfileImport } from './routes/_protected/profile'
import { Route as ProtectedDashboardImport } from './routes/_protected/dashboard'
import { Route as ProtectedUserUserIdImport } from './routes/_protected/user.$userId'
import { Route as ProtectedBooksBookIdImport } from './routes/_protected/books.$bookId'

// Create/Update Routes

const TosRoute = TosImport.update({
  id: '/tos',
  path: '/tos',
  getParentRoute: () => rootRoute,
} as any)

const RegisterRoute = RegisterImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRoute,
} as any)

const LoginRoute = LoginImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const ContactRoute = ContactImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRoute,
} as any)

const AboutRoute = AboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PasswordResetRoute = PasswordResetImport.update({
  id: '/password/reset',
  path: '/password/reset',
  getParentRoute: () => rootRoute,
} as any)

const PasswordForgotRoute = PasswordForgotImport.update({
  id: '/password/forgot',
  path: '/password/forgot',
  getParentRoute: () => rootRoute,
} as any)

const EmailVerifyRoute = EmailVerifyImport.update({
  id: '/email/verify',
  path: '/email/verify',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedSettingsRoute = ProtectedSettingsImport.update({
  id: '/_protected/settings',
  path: '/settings',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedProfileRoute = ProtectedProfileImport.update({
  id: '/_protected/profile',
  path: '/profile',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedDashboardRoute = ProtectedDashboardImport.update({
  id: '/_protected/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedUserUserIdRoute = ProtectedUserUserIdImport.update({
  id: '/_protected/user/$userId',
  path: '/user/$userId',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedBooksBookIdRoute = ProtectedBooksBookIdImport.update({
  id: '/_protected/books/$bookId',
  path: '/books/$bookId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutImport
      parentRoute: typeof rootRoute
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactImport
      parentRoute: typeof rootRoute
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginImport
      parentRoute: typeof rootRoute
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterImport
      parentRoute: typeof rootRoute
    }
    '/tos': {
      id: '/tos'
      path: '/tos'
      fullPath: '/tos'
      preLoaderRoute: typeof TosImport
      parentRoute: typeof rootRoute
    }
    '/_protected/dashboard': {
      id: '/_protected/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof ProtectedDashboardImport
      parentRoute: typeof rootRoute
    }
    '/_protected/profile': {
      id: '/_protected/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProtectedProfileImport
      parentRoute: typeof rootRoute
    }
    '/_protected/settings': {
      id: '/_protected/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof ProtectedSettingsImport
      parentRoute: typeof rootRoute
    }
    '/email/verify': {
      id: '/email/verify'
      path: '/email/verify'
      fullPath: '/email/verify'
      preLoaderRoute: typeof EmailVerifyImport
      parentRoute: typeof rootRoute
    }
    '/password/forgot': {
      id: '/password/forgot'
      path: '/password/forgot'
      fullPath: '/password/forgot'
      preLoaderRoute: typeof PasswordForgotImport
      parentRoute: typeof rootRoute
    }
    '/password/reset': {
      id: '/password/reset'
      path: '/password/reset'
      fullPath: '/password/reset'
      preLoaderRoute: typeof PasswordResetImport
      parentRoute: typeof rootRoute
    }
    '/_protected/books/$bookId': {
      id: '/_protected/books/$bookId'
      path: '/books/$bookId'
      fullPath: '/books/$bookId'
      preLoaderRoute: typeof ProtectedBooksBookIdImport
      parentRoute: typeof rootRoute
    }
    '/_protected/user/$userId': {
      id: '/_protected/user/$userId'
      path: '/user/$userId'
      fullPath: '/user/$userId'
      preLoaderRoute: typeof ProtectedUserUserIdImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tos': typeof TosRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/profile': typeof ProtectedProfileRoute
  '/settings': typeof ProtectedSettingsRoute
  '/email/verify': typeof EmailVerifyRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/books/$bookId': typeof ProtectedBooksBookIdRoute
  '/user/$userId': typeof ProtectedUserUserIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tos': typeof TosRoute
  '/dashboard': typeof ProtectedDashboardRoute
  '/profile': typeof ProtectedProfileRoute
  '/settings': typeof ProtectedSettingsRoute
  '/email/verify': typeof EmailVerifyRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/books/$bookId': typeof ProtectedBooksBookIdRoute
  '/user/$userId': typeof ProtectedUserUserIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/tos': typeof TosRoute
  '/_protected/dashboard': typeof ProtectedDashboardRoute
  '/_protected/profile': typeof ProtectedProfileRoute
  '/_protected/settings': typeof ProtectedSettingsRoute
  '/email/verify': typeof EmailVerifyRoute
  '/password/forgot': typeof PasswordForgotRoute
  '/password/reset': typeof PasswordResetRoute
  '/_protected/books/$bookId': typeof ProtectedBooksBookIdRoute
  '/_protected/user/$userId': typeof ProtectedUserUserIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/tos'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/email/verify'
    | '/password/forgot'
    | '/password/reset'
    | '/books/$bookId'
    | '/user/$userId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/tos'
    | '/dashboard'
    | '/profile'
    | '/settings'
    | '/email/verify'
    | '/password/forgot'
    | '/password/reset'
    | '/books/$bookId'
    | '/user/$userId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/contact'
    | '/login'
    | '/register'
    | '/tos'
    | '/_protected/dashboard'
    | '/_protected/profile'
    | '/_protected/settings'
    | '/email/verify'
    | '/password/forgot'
    | '/password/reset'
    | '/_protected/books/$bookId'
    | '/_protected/user/$userId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  TosRoute: typeof TosRoute
  ProtectedDashboardRoute: typeof ProtectedDashboardRoute
  ProtectedProfileRoute: typeof ProtectedProfileRoute
  ProtectedSettingsRoute: typeof ProtectedSettingsRoute
  EmailVerifyRoute: typeof EmailVerifyRoute
  PasswordForgotRoute: typeof PasswordForgotRoute
  PasswordResetRoute: typeof PasswordResetRoute
  ProtectedBooksBookIdRoute: typeof ProtectedBooksBookIdRoute
  ProtectedUserUserIdRoute: typeof ProtectedUserUserIdRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  TosRoute: TosRoute,
  ProtectedDashboardRoute: ProtectedDashboardRoute,
  ProtectedProfileRoute: ProtectedProfileRoute,
  ProtectedSettingsRoute: ProtectedSettingsRoute,
  EmailVerifyRoute: EmailVerifyRoute,
  PasswordForgotRoute: PasswordForgotRoute,
  PasswordResetRoute: PasswordResetRoute,
  ProtectedBooksBookIdRoute: ProtectedBooksBookIdRoute,
  ProtectedUserUserIdRoute: ProtectedUserUserIdRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/about",
        "/contact",
        "/login",
        "/register",
        "/tos",
        "/_protected/dashboard",
        "/_protected/profile",
        "/_protected/settings",
        "/email/verify",
        "/password/forgot",
        "/password/reset",
        "/_protected/books/$bookId",
        "/_protected/user/$userId"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/about": {
      "filePath": "about.tsx"
    },
    "/contact": {
      "filePath": "contact.tsx"
    },
    "/login": {
      "filePath": "login.tsx"
    },
    "/register": {
      "filePath": "register.tsx"
    },
    "/tos": {
      "filePath": "tos.tsx"
    },
    "/_protected/dashboard": {
      "filePath": "_protected/dashboard.tsx"
    },
    "/_protected/profile": {
      "filePath": "_protected/profile.tsx"
    },
    "/_protected/settings": {
      "filePath": "_protected/settings.tsx"
    },
    "/email/verify": {
      "filePath": "email.verify.tsx"
    },
    "/password/forgot": {
      "filePath": "password.forgot.tsx"
    },
    "/password/reset": {
      "filePath": "password.reset.tsx"
    },
    "/_protected/books/$bookId": {
      "filePath": "_protected/books.$bookId.tsx"
    },
    "/_protected/user/$userId": {
      "filePath": "_protected/user.$userId.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
